[[crates]]
name = "billing"
packages = ["test_helpers", "billing_portal", "billing"]
paths = [
    "credit_note",
    "tax_id",
    "invoice",
    "item",
    "plan",
    "quote",
    "subscription",
]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Billing` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "checkout"
packages = ["checkout"]
description = '''This crate provides Rust bindings to the Stripe HTTP API,
centered around [Checkout Sessions](https://stripe.com/docs/api/checkout/sessions).
'''

[[crates]]
name = "connect"
paths = ["country_spec", "account", "topup", "application_fee", "transfer", "application"]
packages = ["apps"]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Connect` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "core"
paths = [
    "balance",
    "balance_transaction",
    "charge",
    "customer",
    "dispute",
    "event",
    "file",
    "mandate",
    "payment_intent",
    "setup_intent",
    "setup_attempt",
    "payout",
    "refund",
    "token"
]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Core Resources` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "fraud"
paths = ["review"]
packages = ["radar"]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Fraud` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "issuing"
paths = ["funding_instructions"]
packages = ["issuing"]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Issuing` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "payment"
paths = [
    "card",
    "payment_method",
    "source",
    "bank_account",
    "payment_link",
    "confirmation_token",
]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Payment Methods` and `Payment Links` sections
of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "product"
paths = [
    "product",
    "price",
    "coupon",
    "promotion_code",
    "discount",
    "tax_code",
    "tax_rate",
    "shipping_rate",
]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Products` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "terminal"
packages = ["terminal"]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Terminal` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "treasury"
packages = ["treasury"]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Treasury` section of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "misc"
paths = [
    "apple_pay_domain",
    "ephemeral_key",
    "exchange_rate",
    "webhook_endpoint",
]
packages = [
    "tax",
    "identity",
    "reporting",
    "sigma",
    "financial_connections",
    "climate",
    "entitlements",
    "forwarding"
]
description = '''This crate provides Rust bindings to the Stripe HTTP API, specifically
for requests mentioned in the `Tax`, `Identity`, `Reporting`, `Sigma`, `Financial Connections`
and `Webhooks` sections of the [Stripe API docs](https://stripe.com/docs/api)
'''

[[crates]]
name = "shared"
paths = [
    "api_errors",
    "shipping",
    "address",
    # These should not need to be manually specified, but currently
    # cannot have their crate inferred
    "linked_account_options_us_bank_account",
    "subscriptions_trials_resource_trial_settings",
    "radar_radar_options"
]
description = '''Autogenerated types shared between async-stripe-* crates. If you find yourself
needing to depend on this crate, please open an issue, as all useful types should be
reexported.
'''

