[package]
name = "async-stripe-core"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"
name = "stripe_core"

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
smol_str.workspace = true
miniserde.workspace = true
async-stripe-types = {path = "../../async-stripe-types"}
async-stripe-client-core = {path = "../../async-stripe-client-core"}

async-stripe-shared = {path = "../../generated/async-stripe-shared"}


[features]
serialize = ["async-stripe-types/serialize","async-stripe-shared/serialize"]
serialize_extra = ["serialize", "async-stripe-types/serialize_extra","async-stripe-shared/serialize_extra"]
deserialize = ["async-stripe-types/deserialize","async-stripe-shared/deserialize", "dep:serde_json"]
deserialize_extra = ["deserialize", "async-stripe-types/deserialize_extra","async-stripe-shared/deserialize_extra", "dep:serde_json"]
balance = []
balance_transaction = []
cash_balance = []
charge = []
customer = []
customer_balance_transaction = []
customer_cash_balance_transaction = []
customer_session = []
dispute = []
event = []
file = []
file_link = []
mandate = []
payment_intent = []
payment_source = []
payout = []
refund = []
setup_attempt = []
setup_intent = []
token = []

full = ["balance",
"balance_transaction",
"cash_balance",
"charge",
"customer",
"customer_balance_transaction",
"customer_cash_balance_transaction",
"customer_session",
"dispute",
"event",
"file",
"file_link",
"mandate",
"payment_intent",
"payment_source",
"payout",
"refund",
"setup_attempt",
"setup_intent",
"token"]


[package.metadata.docs.rs]
features = ["full"]

