use std::fmt::{Debug, Display, Formatter};

use crate::components::Components;
use crate::rust_object::{DeserDefault, ObjectMetadata, RustObject};
use crate::types::{ComponentPath, RustIdent};
use crate::visitor::{Visitor, VisitorMut};

/// A path to a type defined elsewhere.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub enum PathToType {
    /// A top-level component.
    Component(ComponentPath),
    /// The id for a top-level component.
    ObjectId(ComponentPath),
    /// A type defined in `stripe_types`
    Type(RustIdent),
}

impl PathToType {
    pub fn has_reference(&self, components: &Components) -> bool {
        match self {
            // NB: It would be more future-proof to query reference info
            // directly, e.g. `components.get(path).rust_obj().has_reference(components)`,
            // but this leads to infinite recursion because of the cyclical type definitions
            // in the spec. For now, `false` is always accurate, so is an easy workaround
            PathToType::Component(_) => false,

            // Always either backed by `String` or `smol_str::SmolStr`
            PathToType::ObjectId(_) => false,
            PathToType::Type(ident) => {
                components.get_extra_type(ident).obj.has_reference(components)
            }
        }
    }

    pub fn is_copy(&self, components: &Components) -> bool {
        match self {
            // NB: see cyclical type issues below. This is likely overly
            // conservative, but _most_ components type are far from `copy`, only
            // wrong in a small number of cases that don't affect correctness,
            // just not deriving `Copy` in all possible cases
            PathToType::Component(_) => false,

            // Always either backed by `String` or `smol_str::SmolStr`
            PathToType::ObjectId(_) => false,
            PathToType::Type(ident) => components.get_extra_type(ident).obj.is_copy(components),
        }
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub enum RustType {
    Object(RustObject, ObjectMetadata),
    /// A scalar type (meaning that does not contain another `RustType` internally, not that
    /// it may not be a collection), not generated by codegen.
    Simple(SimpleType),
    Path {
        path: PathToType,
        is_ref: bool,
    },
    /// Type containing an inner type.
    Container(Container),
}

impl RustType {
    pub const fn bool() -> Self {
        Self::Simple(SimpleType::Bool)
    }

    pub const fn float() -> Self {
        Self::Simple(SimpleType::Float)
    }

    pub const fn string() -> Self {
        Self::Simple(SimpleType::String)
    }

    pub const fn int(typ: IntType) -> Self {
        Self::Simple(SimpleType::Int(typ))
    }

    pub const fn ext(ext: ExtType) -> Self {
        Self::Simple(SimpleType::Ext(ext))
    }

    pub fn option(typ: Self) -> Self {
        Self::Container(Container::Option(Box::new(typ)))
    }

    pub fn boxed(typ: Self) -> Self {
        Self::Container(Container::Box(Box::new(typ)))
    }

    pub fn list(typ: Self) -> Self {
        Self::Container(Container::List(Box::new(typ)))
    }

    /// Construct an `Expandable<{typ}>`.
    pub fn expandable(typ: Self) -> Self {
        Self::Container(Container::Expandable(Box::new(typ)))
    }

    /// Construct a `HashMap<String, {typ}>`.
    pub fn str_map(value: Self, is_ref: bool) -> Self {
        Self::Container(Container::Map { key: MapKey::String, value: Box::new(value), is_ref })
    }

    /// Construct a `HashMap<Currency, {typ}>`.
    pub fn currency_map(typ: Self, is_ref: bool) -> Self {
        Self::Container(Container::Map { key: MapKey::Currency, value: Box::new(typ), is_ref })
    }

    /// Construct a `Vec<{typ}>`.
    pub fn vec(typ: Self) -> Self {
        Self::Container(Container::Vec(Box::new(typ)))
    }

    /// Construct a `&[{typ}]`
    pub fn slice(typ: Self) -> Self {
        Self::Container(Container::Slice(Box::new(typ)))
    }

    pub fn path(path: PathToType, is_ref: bool) -> Self {
        Self::Path { path, is_ref }
    }

    pub fn as_id_path(&self) -> Option<&ComponentPath> {
        match self {
            Self::Path { path: PathToType::ObjectId(path), .. } => Some(path),
            Self::Container(typ) => typ.value_typ().as_id_path(),
            _ => None,
        }
    }

    pub fn as_component_path(&self) -> Option<&ComponentPath> {
        match self {
            Self::Path { path: PathToType::Component(path), .. } => Some(path),
            Self::Container(typ) => typ.value_typ().as_component_path(),
            _ => None,
        }
    }

    pub fn implies_private_field(&self) -> bool {
        matches!(self, Self::Simple(SimpleType::Ext(ExtType::AlwaysTrue)))
    }

    /// Is this type `Option<>`?
    pub const fn is_option(&self) -> bool {
        matches!(self, Self::Container(Container::Option(_)))
    }

    /// Can this type derive `Copy`?
    pub fn is_copy(&self, components: &Components) -> bool {
        use Container::*;

        match self {
            Self::Object(obj, ..) => obj.is_copy(components),
            Self::Simple(typ) => typ.is_copy(),
            Self::Path { path, is_ref } => *is_ref || path.is_copy(components),
            Self::Container(typ) => match typ {
                List(_) | Vec(_) | Expandable(_) => false,
                Slice(_) => true,
                Option(inner) | Box(inner) => inner.is_copy(components),
                Map { is_ref, .. } => *is_ref,
            },
        }
    }

    /// Does this contain a reference? Primarily used for detecting types that may
    /// require lifetimes.
    pub fn has_reference(&self, components: &Components) -> bool {
        match self {
            Self::Object(obj, ..) => obj.has_reference(components),
            Self::Simple(typ) => typ.is_reference(),
            Self::Path { path, is_ref } => *is_ref || path.has_reference(components),
            Self::Container(typ) => match typ {
                Container::Slice(_) => true,
                Container::Map { is_ref: true, .. } => true,
                _ => typ.value_typ().has_reference(components),
            },
        }
    }

    pub fn component_path(path: ComponentPath) -> Self {
        Self::path(PathToType::Component(path), false)
    }

    pub fn serde_json_value(is_ref: bool) -> Self {
        Self::Simple(SimpleType::Ext(ExtType::Value { is_ref }))
    }

    pub fn object_id(id_path: ComponentPath, is_ref: bool) -> Self {
        Self::path(PathToType::ObjectId(id_path), is_ref)
    }

    pub fn into_nullable(self) -> Self {
        match self {
            Self::Container(Container::List(_)) | Self::Container(Container::Option(_)) => self,
            _ => Self::option(self),
        }
    }

    pub fn as_skip_serializing(&self) -> Option<&'static str> {
        match self {
            Self::Container(Container::Option(_)) => Some("Option::is_none"),
            _ => None,
        }
    }

    pub fn as_object(&self) -> Option<(&RustObject, &ObjectMetadata)> {
        match self {
            Self::Object(obj, meta) => Some((obj, meta)),
            Self::Simple(_) | Self::Path { .. } => None,
            Self::Container(typ) => typ.value_typ().as_object(),
        }
    }

    pub fn as_object_mut(&mut self) -> Option<(&mut RustObject, &ObjectMetadata)> {
        match self {
            Self::Object(obj, meta) => Some((obj, meta)),
            Self::Simple(_) | Self::Path { .. } => None,
            Self::Container(typ) => typ.value_typ_mut().as_object_mut(),
        }
    }

    pub fn into_object(self) -> Option<(RustObject, ObjectMetadata)> {
        match self {
            Self::Object(obj, meta) => Some((obj, meta)),
            Self::Simple(_) | Self::Path { .. } => None,
            Self::Container(typ) => typ.into_value_typ().into_object(),
        }
    }

    pub fn as_rust_object(&self) -> Option<&RustObject> {
        self.as_object().map(|r| r.0)
    }

    pub fn as_deser_default(&self) -> Option<DeserDefault> {
        match self {
            Self::Simple(SimpleType::Bool)
            | Self::Container(Container::Vec(_))
            | Self::Container(Container::List(_)) => Some(DeserDefault::Default),
            _ => None,
        }
    }

    pub fn visit<T: Visitor>(&self, visitor: &mut T) {
        use RustType::*;
        match self {
            Object(obj, meta) => {
                visitor.visit_obj(obj, Some(meta));
            }
            Simple(_) | Path { .. } => {}
            Container(inner) => visitor.visit_typ(inner.value_typ()),
        }
    }

    pub fn visit_mut<T: VisitorMut>(&mut self, visitor: &mut T) {
        use RustType::*;
        match self {
            Object(obj, meta) => {
                visitor.visit_obj_mut(obj, Some(meta));
            }
            Simple(_) | Path { .. } => {}
            Container(inner) => visitor.visit_typ_mut(inner.value_typ_mut()),
        }
    }
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
pub enum MapKey {
    String,
    Currency,
}

impl Display for MapKey {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::String => "String",
            Self::Currency => "stripe_types::Currency",
        })
    }
}

/// Representation of a type containing an inner type.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub enum Container {
    /// List<{typ}>
    List(Box<RustType>),
    /// Vec<{typ}>
    Vec(Box<RustType>),
    /// &[{typ}]
    Slice(Box<RustType>),
    /// Expandable<{typ}>
    Expandable(Box<RustType>),
    /// Option<{typ}>
    Option(Box<RustType>),
    /// Box<{typ}>
    Box(Box<RustType>),
    /// HashMap<{key}, {typ}>
    Map {
        /// HashMap key type.
        key: MapKey,
        /// HashMap value type.
        value: Box<RustType>,
        /// Are we a reference?
        is_ref: bool,
    },
}

impl Container {
    /// Get a reference to the inner contained type.
    pub fn value_typ(&self) -> &RustType {
        use Container::*;
        match self {
            List(typ) => typ,
            Vec(typ) => typ,
            Slice(typ) => typ,
            Expandable(typ) => typ,
            Option(typ) => typ,
            Box(typ) => typ,
            Map { value, .. } => value,
        }
    }

    /// Extract the inner contained type.
    pub fn into_value_typ(self) -> RustType {
        use Container::*;
        let res = match self {
            List(typ) => typ,
            Vec(typ) => typ,
            Slice(typ) => typ,
            Expandable(typ) => typ,
            Option(typ) => typ,
            Box(typ) => typ,
            Map { value, .. } => value,
        };
        *res
    }

    /// Get a mutable reference to the inner contained type.
    pub fn value_typ_mut(&mut self) -> &mut RustType {
        use Container::*;
        match self {
            List(typ) => typ,
            Vec(typ) => typ,
            Slice(typ) => typ,
            Expandable(typ) => typ,
            Option(typ) => typ,
            Box(typ) => typ,
            Map { value, .. } => value,
        }
    }
}

/// Either a Rust defined scalar type, or a type predefined in `stripe_types`.
#[derive(Copy, Clone, Eq, PartialEq, Hash)]
pub enum SimpleType {
    /// bool
    Bool,
    /// f64
    Float,
    /// &str
    Str,
    /// String
    String,
    /// One of primitive rust integer types.
    Int(IntType),
    /// Type defined in `stripe_types`.
    Ext(ExtType),
}

impl SimpleType {
    /// Does this type implement `Copy`?
    pub const fn is_copy(self) -> bool {
        !matches!(self, Self::String | Self::Ext(ExtType::Value { is_ref: false }))
    }

    /// Is this type a reference?
    pub const fn is_reference(self) -> bool {
        matches!(self, Self::Str | Self::Ext(ExtType::Value { is_ref: true }))
    }

    pub const fn ident(self) -> &'static str {
        use SimpleType::*;
        match self {
            Bool => "bool",
            Float => "f64",
            String => "String",
            Str => "str",
            Int(typ) => typ.as_str(),
            Ext(ext) => ext.ident(),
        }
    }
}

impl Debug for SimpleType {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.ident())
    }
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
pub enum IntType {
    U8,
    U32,
    U64,
    I64,
}

impl IntType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::U8 => "u8",
            Self::U32 => "u32",
            Self::U64 => "u64",
            Self::I64 => "i64",
        }
    }
}

impl Display for IntType {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Types defined outside of codegen.
#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
pub enum ExtType {
    Currency,
    RangeQueryTs,
    Timestamp,
    AlwaysTrue,
    /// serde_json::Value
    Value {
        is_ref: bool,
    },
}

impl ExtType {
    pub const fn ident(self) -> &'static str {
        match self {
            Self::Currency => "stripe_types::Currency",
            Self::RangeQueryTs => "stripe_types::RangeQueryTs",
            Self::Timestamp => "stripe_types::Timestamp",
            Self::AlwaysTrue => "stripe_types::AlwaysTrue",
            Self::Value { .. } => "serde_json::Value",
        }
    }
}
