[package]
name = "stripe_billing"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
smol_str.workspace = true
miniserde.workspace = true
stripe_types = {path = "../../stripe_types"}
stripe_client_core = {path = "../../stripe_client_core"}

stripe_shared = {path = "../../generated/stripe_shared"}


[features]
serialize = ["stripe_types/serialize","stripe_shared/serialize"]
deserialize = ["stripe_types/deserialize","stripe_shared/deserialize", "dep:serde_json"]
billing_meter = []
billing_meter_event = []
billing_meter_event_adjustment = []
billing_meter_event_summary = []
billing_portal_configuration = []
billing_portal_session = []
credit_note = []
credit_note_line_item = []
invoice = []
invoice_item = []
invoice_line_item = []
plan = []
quote = []
subscription = []
subscription_item = []
subscription_schedule = []
tax_id = []
test_helpers_test_clock = []
usage_record = []
usage_record_summary = []

full = ["billing_meter",
"billing_meter_event",
"billing_meter_event_adjustment",
"billing_meter_event_summary",
"billing_portal_configuration",
"billing_portal_session",
"credit_note",
"credit_note_line_item",
"invoice",
"invoice_item",
"invoice_line_item",
"plan",
"quote",
"subscription",
"subscription_item",
"subscription_schedule",
"tax_id",
"test_helpers_test_clock",
"usage_record",
"usage_record_summary"]


[package.metadata.docs.rs]
features = ["full"]

